### PR TITLE
Add optional `url` site option

### PR DESCRIPTION
**Pull request by timurrustamov**
Starting April 14, 2020, Netlify changed the default site deployments from `your-site-name-netlify.com` to `your-site-name-netlify.app`. In order to support those changes, we need alter the default generation of site urls. Furthermore, it would be nice to be able to set your own site urls (in case of custom domains).

I took some time in order to refactor `SiteItem` component to use hooks and to add some tests ! ;)

### CODE REVIEW

**Comment by hacknug** [comment]
Anything we can do to help get this merged in?

**Comment by mornir** [comment]
@kmelve 👀

**Comment by rexxars** [comment]
Thank you so much for contributing this! I've pulled your changes in and applied some formatting changes, and published a new version, [v1.1.0](https://github.com/sanity-io/sanity-plugin-dashboard-widget-netlify/releases/tag/v1.1.0) which includes your changes - thanks again!

**Comment by s-g-k** [comment]
🙏

**Pull request closed without merging**
